// RBAC constants: stable permission & role identifiers plus role->permission mapping.
// Extend by adding new PERMISSIONS keys and including them in relevant ROLES_PERMISSIONS entries.
export const PERMISSIONS = {
  // Core / Dashboard
  VIEW_DASHBOARD: "VIEW:DASHBOARD",

  // Users (existing internal management)
  READ_USERS: "READ:USERS",
  EDIT_USERS: "EDIT:USERS",
  DELETE_USERS: "MANAGE:USERS",
  VIEW_USERS: "VIEW:USERS",

  // Franchises
  READ_FRANCHISES: "READ:FRANCHISES",
  EDIT_FRANCHISES: "EDIT:FRANCHISES",
  DELETE_FRANCHISES: "MANAGE:FRANCHISES",
  VIEW_FRANCHISES: "VIEW:FRANCHISES",

  // States
  READ_STATES: "READ:STATES",
  EDIT_STATES: "EDIT:STATES",
  DELETE_STATES: "DELETE:STATES",
  VIEW_STATES: "VIEW:STATES",

   // Patients
  READ_PATIENTS: "READ:PATIENTS",
  EDIT_PATIENTS: "EDIT:PATIENTS",
  DELETE_PATIENTS: "DELETE:PATIENTS",
  VIEW_PATIENTS: "VIEW:PATIENTS",


  // Services
  READ_SERVICES: "READ:SERVICES",
  CREATE_SERVICES: "CREATE:SERVICES",
  EDIT_SERVICES: "EDIT:SERVICES",
  DELETE_SERVICES: "DELETE:SERVICES",
  VIEW_SERVICES: "VIEW:SERVICES",

  // Medicines
  READ_MEDICINES: "READ:MEDICINES",
  CREATE_MEDICINES: "CREATE:MEDICINES",
  EDIT_MEDICINES: "EDIT:MEDICINES",
  DELETE_MEDICINES: "DELETE:MEDICINES",
  VIEW_MEDICINES: "VIEW:MEDICINES",

  // Sales
  READ_SALES: "READ:SALES",
  CREATE_SALES: "CREATE:SALES",
  EDIT_SALES: "EDIT:SALES",
  DELETE_SALES: "DELETE:SALES",
  VIEW_SALES: "VIEW:SALES",

  // StockAdjustments
  READ_STOCK_ADJUSTMENTS: "READ:STOCK_ADJUSTMENTS",
  CREATE_STOCK_ADJUSTMENTS: "CREATE:STOCK_ADJUSTMENTS",
  VIEW_STOCK_ADJUSTMENTS: "VIEW:STOCK_ADJUSTMENTS",

  // Stocks
  READ_STOCKS: "READ:STOCKS",
  VIEW_STOCKS: "VIEW:STOCKS",

  // Cities
  READ_CITIES: "READ:CITIES",
  EDIT_CITIES: "EDIT:CITIES",
  DELETE_CITIES: "DELETE:CITIES",
  VIEW_CITIES: "VIEW:CITIES",

  // Brands
  READ_BRANDS: "READ:BRANDS",
  CREATE_BRANDS: "CREATE:BRANDS",
  EDIT_BRANDS: "EDIT:BRANDS",
  DELETE_BRANDS: "DELETE:BRANDS",
  VIEW_BRANDS: "VIEW:BRANDS",

  // Rooms
  READ_ROOMS: "READ:ROOMS",
  CREATE_ROOMS: "CREATE:ROOMS",
  EDIT_ROOMS: "EDIT:ROOMS",
  DELETE_ROOMS: "DELETE:ROOMS",
  VIEW_ROOMS: "VIEW:ROOMS",

  //Teams
  READ_TEAMS: "READ:TEAMS",
  CREATE_TEAMS: "CREATE:TEAMS",
  EDIT_TEAMS: "EDIT:TEAMS",
  DELETE_TEAMS: "DELETE:TEAMS",
  VIEW_TEAMS: "VIEW:TEAMS",
  
  // Packages
  READ_PACKAGES: "READ:PACKAGES",
  CREATE_PACKAGES: "CREATE:PACKAGES",
  EDIT_PACKAGES: "EDIT:PACKAGES",
  DELETE_PACKAGES: "DELETE:PACKAGES",
  VIEW_PACKAGES: "VIEW:PACKAGES",
} as const;


export const ROLES = {
  ADMIN: "Admin",
  FRANCHISE: "Franchise",
  DOCTOR: "Doctor",
} as const;

export const ACTIVE_ROLE_CODES = ["ADMIN", "FRANCHISE", "DOCTOR"] as const;

export const ACTIVE_ROLE_LABELS = ACTIVE_ROLE_CODES.map(
  (code) => (ROLES as any)[code]
) as readonly string[];

export const ROLES_PERMISSIONS = {
  // Admin: everything
  [ROLES.ADMIN]: (Object.values(PERMISSIONS) as string[]).filter(
    (p) =>
      p !== PERMISSIONS.READ_PATIENTS &&
      p !== PERMISSIONS.EDIT_PATIENTS &&
      p !== PERMISSIONS.DELETE_PATIENTS &&
      p !== PERMISSIONS.VIEW_PATIENTS 
  ),
  [ROLES.FRANCHISE]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.READ_STATES,
    PERMISSIONS.READ_CITIES,
    PERMISSIONS.VIEW_PATIENTS,
    PERMISSIONS.READ_PATIENTS,
    PERMISSIONS.EDIT_PATIENTS,
    PERMISSIONS.DELETE_PATIENTS,
    PERMISSIONS.READ_ROOMS,
    PERMISSIONS.CREATE_ROOMS,
    PERMISSIONS.EDIT_ROOMS,
    PERMISSIONS.DELETE_ROOMS,
    PERMISSIONS.VIEW_ROOMS,
    PERMISSIONS.READ_TEAMS,
    PERMISSIONS.CREATE_TEAMS,
    PERMISSIONS.EDIT_TEAMS,
    PERMISSIONS.DELETE_TEAMS,
    PERMISSIONS.VIEW_TEAMS,
  ],
  [ROLES.DOCTOR]: [PERMISSIONS.VIEW_DASHBOARD],
} as const;
